// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-vLoHOple6lrCvEdQaj8MmUbErZn-fog',
    appId: '1:449864634871:web:a2a45a886ce32d4035def2',
    messagingSenderId: '449864634871',
    projectId: 'test-a53e9',
    authDomain: 'test-a53e9.firebaseapp.com',
    storageBucket: 'test-a53e9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAiSFyhbN8QIxQUDAD7CbuoJi0YaaaD0t8',
    appId: '1:449864634871:android:3292ce11d8bcde5835def2',
    messagingSenderId: '449864634871',
    projectId: 'test-a53e9',
    storageBucket: 'test-a53e9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqrNrfW9JRX2E39Bd1ln0RXln7u4_5fe0',
    appId: '1:449864634871:ios:dd4eddb9c35ec10635def2',
    messagingSenderId: '449864634871',
    projectId: 'test-a53e9',
    storageBucket: 'test-a53e9.appspot.com',
    iosBundleId: 'com.example.loginScreen',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqrNrfW9JRX2E39Bd1ln0RXln7u4_5fe0',
    appId: '1:449864634871:ios:719e16ea5101ebf535def2',
    messagingSenderId: '449864634871',
    projectId: 'test-a53e9',
    storageBucket: 'test-a53e9.appspot.com',
    iosBundleId: 'com.example.loginScreen.RunnerTests',
  );
}
